package com.aash.optimizer

import android.app.Activity
import android.content.Intent
import android.graphics.Color
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.util.Log
import android.view.ViewGroup
import android.webkit.ConsoleMessage
import android.webkit.WebChromeClient
import android.webkit.WebResourceRequest
import android.webkit.WebResourceResponse
import android.webkit.WebSettings
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.webkit.WebViewAssetLoader

/**
 * Optimizer V.4.0 - native shell.
 *
 * Loads the exact same dashboard that runs as a web page (assets/www, generated by
 * tools/sync-web-assets.sh from ../../index.html and ../../src) over a secure local origin,
 * and exposes the real Android control surface to it as `window.OptimizerNative`.
 *
 * The web layer asks this shell for capabilities; anything Android can really do is answered
 * natively here, and anything Android forbids for a non-root app is reported as such instead of
 * being faked.
 */
class MainActivity : Activity() {

    private val native = NativeBridge()

    lateinit var engine: OptimizerEngine
        private set
    lateinit var webView: OptimizerWebView
        private set

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        native.load()
        engine = OptimizerEngine(this, native)
        val api = JsApi(this)

        webView = OptimizerWebView(this, engine)
        webView.setBackgroundColor(Color.parseColor("#05070F"))
        webView.layoutParams = ViewGroup.LayoutParams(
            ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT
        )

        with(webView.settings) {
            javaScriptEnabled = true
            domStorageEnabled = true
            databaseEnabled = true
            mediaPlaybackRequiresUserGesture = false
            allowFileAccess = false
            allowContentAccess = false
            setSupportZoom(false)
            builtInZoomControls = false
            displayZoomControls = false
            textZoom = 100
            useWideViewPort = false
            loadWithOverviewMode = false
            cacheMode = WebSettings.LOAD_DEFAULT
            userAgentString = userAgentString + " OptimizerV4"
        }

        WebView.setWebContentsDebuggingEnabled(BuildConfig.DEBUG)
        webView.addJavascriptInterface(api, "OptimizerNative")

        val loader = WebViewAssetLoader.Builder()
            .addPathHandler("/assets/", WebViewAssetLoader.AssetsPathHandler(this))
            .build()

        webView.webViewClient = object : WebViewClient() {
            override fun shouldInterceptRequest(view: WebView, request: WebResourceRequest): WebResourceResponse? {
                return try {
                    loader.shouldInterceptRequest(request.url)
                } catch (t: Throwable) {
                    null
                }
            }

            override fun shouldOverrideUrlLoading(view: WebView, request: WebResourceRequest): Boolean {
                val url: Uri = request.url
                if (url.host == "appassets.androidplatform.net") return false
                return try {
                    startActivity(Intent(Intent.ACTION_VIEW, url).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK))
                    true
                } catch (t: Throwable) {
                    true
                }
            }
        }

        webView.webChromeClient = object : WebChromeClient() {
            override fun onConsoleMessage(m: ConsoleMessage): Boolean {
                Log.i("OptimizerWeb", m.message() + " @" + m.lineNumber())
                return true
            }
        }

        setContentView(webView)
        webView.loadUrl("https://appassets.androidplatform.net/assets/www/index.html")
    }

    override fun onResume() {
        super.onResume()
        eval("window.__optimizerResume && window.__optimizerResume()")
    }

    override fun onPause() {
        eval("window.__optimizerPause && window.__optimizerPause()")
        super.onPause()
    }

    @Suppress("DEPRECATION")
    override fun onBackPressed() {
        eval("(window.__optimizerBack && window.__optimizerBack()) ? '1' : '0'") { handled ->
            if (handled != "1") finish()
        }
    }

    private fun eval(js: String, cb: ((String) -> Unit)? = null) {
        try {
            if (cb == null) webView.evaluateJavascript(js, null)
            else webView.evaluateJavascript(js) { v -> cb(v) }
        } catch (t: Throwable) {
        }
    }

    override fun onDestroy() {
        engine.stopHints()
        try {
            webView.destroy()
        } catch (t: Throwable) {
        }
        super.onDestroy()
    }
}
